apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: project-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: frontend-svc
          servicePort: 80
      - path: /backend/*
        backend:
          serviceName: backend-svc
          servicePort: 80