apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  namespace: project-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: FRONTEND/IMAGE
          imagePullPolicy: Always