apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: project-ns
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
