apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: shared-file
          persistentVolumeClaim:
            claimName: backend-claim
      containers:
        - name: backend
          image: BACKEND/IMAGE
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: project-env
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: project-env
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: project-env
                  key: db_name
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files
            subPath: app-files